name: Build and Test Smart_Store

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3

    - name: 🧰 Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: 🏗️ Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: 🔨 Build Smart_Store
      run: |
        cd build
        cmake --build .

    - name: ▶️ Run Smart_Store Output App
      run: |
        cd build
        ./TestApp
